-- Replace the UUID below with your real company id
SET @company_id = '11111111-1111-1111-1111-111111111111';

-- Optional: keep only one default template per company+document type
UPDATE DocumentTemplates
SET IsDefault = 0
WHERE CompanyId = @company_id
  AND DocumentType IN ('RC','TI');

-- Default template for Receipt (RC)
INSERT INTO DocumentTemplates
(TemplateId, CompanyId, DocumentType, TemplateName, LogoUrl, HeaderText, FooterText, IsDefault, IsActive, CreatedAt, UpdatedAt)
VALUES
(UUID(), @company_id, 'RC', 'RC Default Template', 'https://cdn.example.com/logo-rc.png',
 'Thank you for your payment', 'Please contact billing@example.com for support', 1, 1, NOW(), NOW());

-- Default template for Tax Invoice (TI)
INSERT INTO DocumentTemplates
(TemplateId, CompanyId, DocumentType, TemplateName, LogoUrl, HeaderText, FooterText, IsDefault, IsActive, CreatedAt, UpdatedAt)
VALUES
(UUID(), @company_id, 'TI', 'TI Default Template', 'https://cdn.example.com/logo-ti.png',
 'Official Tax Invoice', 'Generated by BillingService', 1, 1, NOW(), NOW());

-- Verify
SELECT TemplateId, CompanyId, DocumentType, TemplateName, IsDefault, IsActive
FROM DocumentTemplates
WHERE CompanyId = @company_id
ORDER BY DocumentType, UpdatedAt DESC;
